export const POKEMONS_FETCH_INIT = 'POKEMONS_FETCH_INIT';
export const POKEMONS_FETCH_SUCCESS = 'POKEMONS_FETCH_SUCCESS';
export const POKEMONS_FETCH_FAILURE = 'POKEMONS_FETCH_FAILURE';
export const SET_FILTER = 'SET_FILTER';